# Funding configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: jonykchen

# Custom links
custom: 
  - 'https://buymeacoffee.com/jonychen'
