spring.application.name=LangChain4j Spring Boot Example
server.port=8082

# Alibaba Cloud DashScope OpenAI-compatible API configuration
# Doc: https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-calling-api
langchain4j.open-ai.chat-model.api-key=sk-7a5a4473f7794045ab763962402e608e
langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.chat-model.model-name=qwen-plus

langchain4j.open-ai.streaming-chat-model.api-key=sk-7a5a4473f7794045ab763962402e608e
langchain4j.open-ai.streaming-chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.streaming-chat-model.model-name=qwen-plus

logging.level.dev.langchain4j=DEBUG

management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1
